### ISSUE TITLE
Use intellij, not eclipse

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#14]
- [x] intellij 설치
- [x] 기본 단축키 익히기 
- [x] hello world java 프로그램 실행해보기
- [x] intellij 기본 내장 formatter 단축키 익히기 
- [x] java google style guide를 intellij에 적용하기

위 내용 작업 이후에 결과를 여기에 작성해주세요

**Comment by Gyoung-min** [comment]
해당 조건을 모두 수행했습니다

**Comment by lette1394** [comment]
@Gyoung-min 
고생하셨습니다. 
앞으로는 intellij를 기본 IDE로 사용해주세요

close 합니다
