### ISSUE TITLE
Buy design pattern book

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#15]
다음 중 마음에 드는 디자인 패턴 책을 하나 골라 구매해주세요. 
급하진 않습니다. 

### Head first Design pattern
http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788979143409

- ### Java 언어로 배우는 디자인 패턴 입문

http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788931436914

**Comment by Gyoung-min** [comment]
네 해당 내용 확인했습니다

**Comment by lette1394** [comment]
@Gyoung-min 
뭐 사셨어요?ㅋㅋㅋ

**Comment by Gyoung-min** [comment]
아직 안샀는데요 스프링 객체지향 1회독 끝나면 비교해보고 사겠습니다

**Comment by Gyoung-min** [comment]
@lette1394 
Head first Design pattern 책 받았습니다

**Comment by lette1394** [comment]
@Gyoung-min 
좋습니다 close 하겠습니다!

**Comment by lette1394** [comment]
> 내용을 비교해보고 읽기 편한걸로 선택하고 커밋 달겠습니다

커밋이 아니라 답글을 달겠다는거죠?ㅎㅎ
일단은 close 했습니다
