### ISSUE TITLE
Java build tools

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#21]
### Java build tools
- `빌드`란 무엇인지 알아보고 정리해주세요
- `빌드 도구`란 무엇인지 알아보고 정리해주세요
- `빌드 도구`는 왜 나왔고, 어떤 문제를 해결하는지 조사해보세요
- `빌드 도구`가 나오기 전에는 개발자들이 어떤 고통을 감내했는지 알아보세요
- hint: `maven`, `gradle`
- 되도록이면 영어로 검색하는걸 추천합니다

**Comment by Gyoung-min** [comment]
## 빌드란?

  - 소스코드 파일을 실행가능한 소프트웨어 산출물로 만드는 일련의 과정을 의미한다. 빌드에서 컴파일 , 테스트 , 배포 등 과정이 포함될 수 있고 , 빌드 과정을 도와주는 도구를 빌드 툴이라 한다.

## 빌드툴(도구)

  - 정형화된 작업을 자동화하기 위한 소프트웨어
  - 일반적인 빌드 툴에서 빌드 순서를 빌드 스크립트로 작성해서 실행하면 다양한 작업을 자동화 할수 있다.
  - 빌드 메뉴얼이 실행 가능한 형태가 되면 다음과 같은 장점이 있다.
    1. 정형화된 작업에 사람이 관여하지 않아도 되니 실수가 줄어든다.
    2. 빌드 스크립트는 항상 관리되므로 문서처럼 낡은 정보가 될 위험이 줄어든다
    3. 조건 분기를 이용해 각 환경에 따른 처리가 가능하다.

## 빌드 툴의 사용 이유

  - 대규모 프로젝트에선 빌드프로세스를 수동으로 호출이 실용적이지 않다. 무엇을 빌드할지, 어떤 순서로 할지, 어떤 의존성이 있는지 모두 추척하기 쉽지 않기 때문이다. 빌드 도구를 사용하면 이를 일관되게 할 수 있다.

## 빌드 툴의 역사

  - Make
     - 유닉스 운영체제에서 사용되는 툴로 메이크 이전에는 수작업이나 약간의 스크립트를 장성해야만 가능했던 작업을 Makefile이라는 통일된 구조로 처리할 수 있게 되었다.
  - Ant
     - 1990년대 자바의 등장
     - Make를 자바에 적용하려고 하니 발생하는 문제를 해결하기 위해 등장
     - 당시 유행했던 자바와 XML 기술을 도입함으로써 Make의 단점이었던 플랫폼 의존 문제를 해결할 수 있게 해주었다.
     - 간단하고 사용하기 쉽다는 장점이 있지만 복잡한 처리에는 빌드 스크립트가 장황해져 관리하기 어렵다
  - Maven
     - 엔트의 문제를 해결하고자 등장했다
     - 자바와 XML을 사용해서 플랫폼 독립성을 확보하는 것은 앤트와 같지만 빌드 생명주기와 프로젝트 객체 모델이라는 새로운 개념을 도입하여 앤트의 약점이었던 장황한 빌드 스크립트 문제를 해결했다
     - POM에 메타 데이터를 적용해서 라이브러리 의존관계를 자동으로 관리해주는 기능을 구현
     - 암묵적인 규칙이 많고 규칙에 벗어난 처리에는 사용이 어렵다는 단점이 존재
  - Gradle
     - 지금까지의 빌드 툴이 가진 장점과 에코시스템을 활용하고 약점운 제거하는 것을 목표로 만들어진 빌드 툴
 
![빌드](https://user-images.githubusercontent.com/78856207/122609571-2c8e9100-d0b9-11eb-8fe5-c5862e811d29.PNG)

**Comment by lette1394** [comment]
@Gyoung-min 
- 아주 잘 찾아주셨습니다ㅎㅎ
- 샘플 프로젝트를 한 번 해보는게 좋을 거 같은데, 요건 다음 아이템으로 진행해볼게요
- close 합니다 고생하셨어요
