### ISSUE TITLE
Github student developer pack

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#24]
- 혹시 `ac.kr` 으로 끝나는 학교 email 주소를 가지고 있으신가요
- github **student** developer pack을 얻을 수 있으면 얻어주세요
- 나중에 intellij에서 spring framework 사용하려면 intellij 유료 버전을 사용해야하는데, 이 학생 계정이 있으면 무료로 사용할 수 있습니다

https://education.github.com/

**Comment by Gyoung-min** [comment]
학생 계정이 학교 웹 메일을 의미하는거라면 없습니다. 없어서 회원 가입을 시도해 봤는데 재학생은 가입이 불가능 하다고 합니다 근데 제 재적 사항은 졸업생으로, 졸업증까지 받았는데 재학생이라 가입이 불가능 하다라는게 이해가 되지 않습니다

**Comment by lette1394** [comment]
@Gyoung-min 
맞아요. 학교 웹 메일을 말한거였어요. 메일 주소가 `ac.kr`로 끝나는.
이상하네요. 보통 웹 메일은 자동으로 생성되는데... 학교의 통합정보시스템 이런데에 한 번도 로그인 한 적이 없나요?

**Comment by lette1394** [comment]
@Gyoung-min 
일요일에 말씀드린대로 학교에 전화해서 꼭꼭 받아내세요~
수십만원 상당의 가치가 있습니다

**Comment by lette1394** [comment]
@Gyoung-min 진행상황이 어떻게 되나요?

**Comment by Gyoung-min** [comment]
연락을 취해봤는데 학교 측에서는 아마 안된다고 합니다
동기 이메일을 빌려서 해보는건 어떤가요?

**Comment by lette1394** [comment]
@Gyoung-min 
흠 그게 가능하다면... 좋긴한데... 
졸업생이 왜 안되지ㅜ 일단 알겠습니다. 안된다고 봐야겠네요

이슈는 close 할게요.
