### ISSUE TITLE
2021-06-17 daliy logs

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/algorithm_prectice#26]
## 오늘 한 공부

<do-it 알고리즘>

  - 1000 이하의 소수를 열거하시오

```
 public static void main(String[] args) {
        int counter = 0;            

        for (int number = 2; number <= 1000; number++) {
            int div;
            for (div = 2; div < number; div++) {
                counter++;
                if (number % div == 0)
                    break;
            }
            if (number == div)
                System.out.println(number);
        }

        System.out.println("나눗셈을 수행한 횟수：" + counter);
    }
```

## 회고

**Comment by lette1394** [comment]
@Gyoung-min 

- google java style은 indent가 `2 space`입니다. 이렇게 적용해주세요
- `나눗셈을 수행한 횟수:` 가 `counter`라면, `counter`라는 변수 이름을 `나눗셈을 수행한 횟수`를 나타내도록 변경해주세요
- `if`에 걸리는 실행 코드가 한 줄이라도, 중괄호를 입력하는게 google code convention 입니다. (아니라면 확인해보고 알려주세요)
- indent level을 최대 1까지만 나타날 수 있도록 코드를 작성해보세요
  - `for`안에 또 `for`를 사용하면, indent(들여쓰기) 수준이 하나 증가하죠?
  - 별도의 메서드를 추가해서 2 단계 이상 들여쓰지 않도록 다시 코드를 작성해보세요. 
  - 당연히 기능은 그대로여야 합니다

**Comment by Gyoung-min** [comment]
이중 for 문, 변수 이름 피드백을 받아 다음과 같이 수정했습니다.

```
package com.company;

public class PrimeNumber {

  static int divisionCounter = 0;

  public static void main(String[] args) {


    int number;
    for (number = 2; number <= 1000; number++) {
      divisionAction(number);

    }
    System.out.println("횟수: " + divisionCounter);
  }

  public static void divisionAction(int number) {


    int division;


    for (division = 2; division < number; division++) {

      divisionCounter++;


      if (number % division == 0) {

        break;
      }

    }
    if (number == division) {

      System.out.println(number);//횟수: 78190
    }


  }

}
```

**Comment by lette1394** [comment]
@Gyoung-min 
### 아래처럼 불필요한 라인을 없애주세요ㅎㅎ 빈 줄이 너무 많습니다

```java
package com.example;

public class Main2 {
  static int divisionCounter = 0;

  public static void main(String[] args) {
    int number;
    for (number = 2; number <= 1000; number++) {
      divisionAction(number);
    }
    System.out.println("횟수: " + divisionCounter);
  }

  public static void divisionAction(int number) {
    int division;
    for (division = 2; division < number; division++) {
      divisionCounter++;
      if (number % division == 0) {
        break;
      }
    }
    if (number == division) {
      System.out.println(number);
    }
  }
}
```

### indent를 `1`으로 만들 수는 없을까요? 
![CleanShot 2021-06-27 at 15 49 06@2x](https://user-images.githubusercontent.com/25474248/123535519-46863e80-d75f-11eb-9110-1d188ae5c456.png)
- `for` 안에 `if` 가 있어서 indent가 `2`가 되었습니다
- 이걸 `1`로 만들어보세요


### 메서드는 하나의 일만 해야합니다
- `divisionAction()` 메서드는 몇 가지 일을 하는지 세어보세요
- 하나의 일만 하도록 수정해보세요
- hint: 상태 변경

### 매직 넘버가 많습니다
- 매직 넘버가 무엇인지 모른다면, 조사 후 정리해주세요
- 어떻게 없앨 수 있을까요?

**Comment by Gyoung-min** [comment]
- 매직 넘버
  - 설명 없이 무작정 등장하는 상수
      - 예를 들어 학생의 학적 상태를 "1이면 재학, 2이면 휴학, 3이면 제적, 4이면 졸업"으로 나타낸다고 가정하자. 이 경우, "이 학생이 졸업 했는가"를 따지기 위해 "학생.상태==1" 따위로 나타낼 경우. 이런 식으로 설명 없이 등장하는 상수를 바로 "매직 넘버"라고 한다
      - 얼핏 보면 매직 넘버를 사용하는 것이 코드가 짧아져서 편해 보일 거라고 생각할 수 있겠지만, 이 역시 코드를 스파게티화시키는 요인 중 하나로 이런 짓을 하게 되면 유지보수의 어려움이 생긴다.
      - 코드 상단에 상수로 지정하거나, 열거형으로 선언하는 습관을 들일 수 있도록 하자

**Comment by lette1394** [comment]
> 얼핏 보면 매직 넘버를 사용하는 것이 코드가 짧아져서 편해 보일 거라고 생각할 수 있겠지만, 이 역시 코드를 스파게티화시키는 요인 중 하나로 이런 짓을 하게 되면 유지보수의 어려움이 생긴다.

매직 넘버를 많이 사용하는 것이 "왜" 어려워질지도 같이 생각해보세요. "매직넘버는 무조건 나쁜 것!"은 또 아닙니다. 언제 이게 필요하고 언제 괜찮은지 구분하는게 중요해요.

여행지 추천 프로젝트에서 고생했던 기억을 떠올려보며...

**Comment by Gyoung-min** [comment]
## 매직 넘버의 허용
다음과 같은 경우 이름없는 숫자 상수의 사용이 허용됩니다
  1. 0과 1을 초기 또는 증분 값으로 사용하는 for 루프
  2. 2를 사용하여 숫자가 짝수인지 홀수인지 확인하는 경우
  3. 간단한 산술 상수 사용
  4. 미터법 값을 변환하거나 백분율을 계산하기 위해 10의 거듭제곱을 사용하는 경우
  5. 표현식의 지수

**Comment by lette1394** [comment]
@Gyoung-min 
피드백 적용해서 다시 코드 작성해주세요~

**Comment by lette1394** [comment]
@Gyoung-min 진행상황 알려주세용

**Comment by Gyoung-min** [comment]
17~19일 데일리 로그는 자바 객체지향 디자인 패턴을 끝낸 후 다시 해당 문제의 코드를 공부한 개념을 녹여 새롭게 작성해볼 예정입니다.

**Comment by lette1394** [comment]
@Gyoung-min 
음. 이 정도 코드는 디자인패턴을 적용할만한 사이즈가 아니라서요...
넵. 제가 별도 이슈를 생성할게요.
