### ISSUE TITLE
2021-06-18 error report

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/algorithm_prectice#27]
## 문제점

  - index.jsp를 실행시 404 에러 발생

## error 메시지

  - 파일 [/sawon/index.jsp]을(를) 찾을 수 없습니다.
  - 심각: Context initialized 이벤트를 [org.springframework.web.context.ContextLoaderListener] 클래스의 인스턴스인 리스너에 전송하는 동안 예외 발생
  - org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in ServletContext resource [/WEB-INF/spring/root-context.xml]: Invocation of init method failed; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [D:\java-workspace-project\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\springmybatis_select_\WEB-INF\classes\mapper\Mapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: java.lang.IllegalArgumentException: Mapped Statements collection already contains value for com.empmanage.sawon.service.dao.SawonDAO.getAllSawon

## 원인 파악

  - 프로그램이 index.jsp에서 시작해서 controller 를 거쳐 dao 처리 후 mapper를 거쳐 db 처리 후 다음 jsp로 리턴한다.
  - 원인을 다음 3가지로 생각한다
    - 메시지처럼 index.jsp가 존재하지 않는다.
    - 실행 시 controller / DB table에 문제가 있다
    - Mapper.xml에 문제가 있다.

## 작업

  - 메시지처럼 index.jsp가 존재하지 않는다
    - index.jsp는 존재하며 다음과 같다.
```
<%@ page language="java" contentType="text/html; charset=euc-kr"
    pageEncoding="euc-kr"%>
<!DOCTYPE html>
<html>      <head>             
<meta charset="euc-kr">
<title>Insert title here</title>
</head>

<body>
	<h1>사원 관리 시작</h1>	<hr>
	<script>
	location.href="sawonAll.do"
	</script>
	
	</body>
</html>

```
  - 실행 시 controller / DB table에 문제가 있다 
    - controller에 "/sawonAll.do"가 존재, DB table도 이상이 없음이 확인되었다
```
@Controller
public class HomeController {

	@Resource(name = "sawonService")  ////////////////
	private SawonService sawonService;//////////

	@RequestMapping(value = "/sawonAll.do")
	public String sawonAll(Model model) throws Exception  {

	    ArrayList<SawonVO> alist = sawonService.getAllSawon();

	    //logger.info(list.toString());

	    model.addAttribute("alist", alist);

	    return "sawonAll"; 
	}
```

```
insert into teltable55
values (1,'ondal','010-7878-3215');

insert into teltable55
values (2,'kongjoo' , '010-3333-7777');

commit;
```

  - Mapper.xml 문제
    - Mapper.xml에 몇가지 빠진 로직을 발견하였다, 수정 이전의 코드는 다음과 같다
```
<mapper namespace="com.empmanage.sawon.service.dao.SawonDAO">
  

	
	<select id="getAllSawon" resultType="sawonVO">
	SELECT id, name, tel
		FROM teltable55
	</select>
	
	<select id="getTelinfo" resultType="sawonVO">
	SELECT id, name, tel
		FROM teltable55 where name = #{name}
							
	</select>
```

## 수정 및 결과

  - Mapper.xml에 빠진 로직을 넣어서 404 오류는 해결했으며 그 로직은 다음과 같다.
```
	<select id="getAllSawon" resultType="sawonVO"> 
	SELECT id, name, tel
	  FROM teltable55
	</select>

	  
    <select id="getTelinfo" resultType="sawonVO">
	  SELECT id, name, tel
	   FROM teltable55  where name=#{name} 
    </select>
                                
   
   
   <insert id="insertSawon">
	  INSERT INTO  teltable55 
	  VALUES (#{id}, #{name},#{tel})
    </insert>
   
   
   
   
    <update id="updateTelinfo">
    update TelTable55 set id=#{id}, tel=#{tel} where name=#{name}
    </update>
    <delete id="deleteTelinfo">
    delete from TelTable55 where name=#{name}
    </delete>
```

## 원인 분석

  - 해당 프로그램은 앞에서 언급한것과 같이 index.jsp에서 시작해서 controller 를 거쳐 dao 처리 후 mapper를 거쳐 db 처리 후 다음 jsp로 리턴한다

  - dao는 다음과 같다
```
public interface SawonDAO { 
	ArrayList <SawonVO> getAllSawon();
	
	void insertSawon(SawonVO sawonVO);
	SawonVO getTelinfo(SawonVO sawonVO);
	void updateTelinfo(SawonVO sawonVO);
	void deleteTelinfo(SawonVO sawonVO);
}
```
  - 수정 전 Mapper.xml에  `insertSawon` , `updateTelinfo` , `deleteTelinfo` 관련 로직이 빠저있어 해당 오류가 발생한 것 같다.

**Comment by lette1394** [comment]
@Gyoung-min 
- 매우매우 잘 정리해주셨습니다!
- "그냥 이거 수정하니까 잘 돌더라~~"하고 그냥 넘어가는거랑, 이렇게 뭐가 문제였고 내 예상은 무엇이었고 등등을 기록하는 과정이 있는거랑은 매우 달라요
- 한 번 더 논리적으로 정리하면서 다음에 비슷한 문제가 생겼을 때, 이 경험이 도움이 될 수 있습니다
- 앞으로는 제가 따로 말씀드리지 않아도 이렇게 정리해서 올려주세요
- 고생 많으셨습니다 👍💯
