### ISSUE TITLE
Use git, github 

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#31]
일요일에 기본적인 `git`의 배경이나 개념들을 아~주 간략히 알아봤죠?
이제 본격적으로 git을 공부해봅시다
- 첫 PR을 날려봅시다!
  - PR이 뭔지 확인합니다
  - 이게 왜 필요한지 배경을 공부합니다 (이건 이제 말 안해도 항상...)
  - 첫 PR을 날려보고 merge 해 봅니다

### 참고자료
1. (입문편부터 천천히 따라해보세요) https://backlog.com/git-tutorial/kr/ 
2. (위 내용을 숙지했으면) https://wayhome25.github.io/git/2017/07/08/git-first-pull-request-story/
  - 이 방법으로 아래 repository에 java 알고리즘 문제를 하나 작성하여 PR을 날려주세요
  - https://github.com/lette1394/git-practice

**Comment by Gyoung-min** [comment]
간단한 알고리즘 문제 push 했습니다

**Comment by lette1394** [comment]
@Gyoung-min 
commit message style, 다음을 참고해서 commit 해주세요
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Gyoung-min** [comment]
## commit message style
1. 목적
  - Commit Message를 통해서 추가/수정 사항에 커밋 메시지만으로 파악이 가능하고, 빠르게 원하는 커밋 내용을 확인하고 파악하는데 목적이 있다.
2. 메시지 구조
  - 커밋 메시지의 기본적인 구조는 `제목`, `본문`, `꼬리말` 3개의 구역으로 나누며, 각 구역은 한 칸의 빈 줄로 구분한다.
```
type: [#issueNumber - ]Subject

Body

Footer
```
  - 가이드 내용이 적용된 예시는 다음과 같다.
```
 feat: Summarize changes in around 50 characters or less

 More detailed explanatory text, if necessary. Wrap it to about 72
 characters or so. In some contexts, the first line is treated as the
 subject of the commit and the rest of the text as the body. The
 blank line separating the summary from the body is critical (unless
 you omit the body entirely); various tools like `log`, `shortlog`
 and `rebase` can get confused if you run the two together.

 Explain the problem that this commit is solving. Focus on why you
 are making this change as opposed to how (the code explains that).
 Are there side effects or other unintuitive consequenses of this
 change? Here's the place to explain them.

 Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded
    by a single space, with blank lines in between, but conventions
    vary here

 If you use an issue tracker, put references to them at the bottom,
 like this:

 Resolves: #123
 See also: #456, #789
```
3. 제목
  - 제목은 항시 입력해야 하며 반드시 타입과 함께 작성되어야 한다.
  - `type: [#issueNumber - ]Subject` 형태로 작성해야 한다.
    - 개인/팀 스타일에 따라 type과 subject의 위치 또는 표현 방식( : 대신 [] )은 변경해도 괜찮다. 다만, 반드시 제목은 작성해야 하며, 제목에는 `type`과 `Subjcet`가 함께 작성되어야 한다.
    - [] 안의 내용은 옵션이며 Github등 이슈 트래킹이 가능한 도구를 함께 사용한다면 #1234와 같은 이슈 트래킹에서 제공하는 이슈 번호를 제목 앞에 넣어주면 된다. ex) feat: #1234 - 회원 생성 서비스 추가
    - 하나의 이슈에 대한 처리일 경우 이슈 번호를 다는 것도 좋지만 여러 개의 이슈가 합쳐진 경우 제목에 이슈 번호를 달지 않는 것이 더 좋다.
  - 타입은 영문 소문자로 작성한다.
  - 제목은 최대 50자를 넘지 않도록 주의 한다.
  - 제목은 해당 커밋에 대한 주요 내용을 간략하게 기록한다.
    - 동사 원형(명령조)로 작성한다.
    - 커밋 메시지는 50자를 넘지 않는 한도 내에서 작업한 내용을 의미하도록 작성해야 한다.
    - 구문 형태, 과거 형태 중 하나를 선택해야 한다
      - ex) 구문: 회원 생성 서비스 추가
               과거: 회원 생성 서비스를 추가함
      - 커밋의 내용을 한번에 표현할 수 있는 제목이 가장 이상적이다
    - 제목의 마지막에 마침표를 찍지 않는다.
4. 타입의 종류
  - 타입의 모든 종류를 사용할 필요는 없다. 프로젝트의 성격이나 상황에 맞추어 적절하게 골라서 사용한다.
    - `feat` : 새로운 기능을 추가하거나 기존의 기능을 요구 사항 변경으로 변경한 경우 기능 추가와 수정을 나누어서 쓰고 싶은 경우 아래 처럼 2개로 나누어서 타입을 지정할 수 있다.
      - `new` : 새로운 개능을 추가 한 경우
      - `improve` : 기존 기능을 수정 한 경우, 요구 사항이 변경되어 수정된 경우에도 improve 타입으로 한다.
    - `fix` : 기능상 버그 픽스를 했을 경우
    - `docs` : 문서(주석)의 추가/수정의 경우, 직접적인 코드의 변화 없이 순수하게 문서(주석)만 추가/수정했을 경우
    - `style` : UI를 추가/변경하거나 스타일 관련 작업을 했을 경우
    - `refactory` : 기능의 변화가 아닌 코드를 리팩토링했을 경우, 코드 리퓨 등으로 로직(기능) 변화 없이 단순 함수 내부에서만 사용하는 이름을 변경하였거나, 코드 pretty 등을 적용했을 경우
    - test : 테스트 코드를 별도로 추가하거나, 변경했을 경우, 만약 기능을 추가하면서 테스트 코드를 동시에 작성했으면 feat 타입으로 사용
    - `chore` : 기능/테스트 코드, 문서, 스타일, 리팩토링을 제와한, 배포, 빌드 등과 같이 프로젝트의 기타 작업들에 대한 추가/수정했을 경우, lint 등의 적용으로 코드 스타일을 수정 했을 때도 chore 사용
    - `release` : 릴리즈를 하기 위해 패키지 버전을 올리거나, 릴리즈 버전 커밋을 찍기 위한 경우
5. 본문
  - 커밋에서 수정된 상세 내역을 작성한다. 여기선 평서문으로 작성한다.
  - 본문은 생략 가능하며, 제목라인과 반드시 한 줄 띄운다.
  - 되도록 한 줄에서 50~72자 이하로 작성하고 길어질 경우 개행해서 다음 줄에 입력한다
  - 수정 내역을 블릿 기호(*) 이용해서 하나씩 입력하는 방법도 있다
  - 본문의 내용은 어떻게 보다는 무엇을 왜에 맞춰 작성한다.
    - 본문에는 이 커밋이 무엇을 왜 고쳤는지 적혀 있는 것이 나중에 히스토리 파악하거나, 코드의 변경 의미를 파악하기에 훨씬 도움이 된다.
    - 어떻게 고쳐졌는지는 코드의 히스토리를 통해 충분히 파악할 수 있으니 반드시 무엇을 왜 했는지에 대해 작성하도록 한다.
6. 꼬리말
  - 꼬리말을 해당 커밋과 연관된 이슈 트래킹 번호를 입력한다.
  - 제목에는 커밋이 온전히 한 개의 이슈에 해당하는 경우에만 추가해서 사용하고 그 외의 경우 대부분 꼬리말에 이슈 번호를 라벨과 함께 추가한다.
  - 꼬리말은 생략 가능하며, 반드시 제목 또는 본문 라인과는 반드시 한 줄 띄운다
 ```
Resolves: #1234
 See also: #1235, #1236
```
7. 라벨의 종류
  - `Resolves` : 문의나, 요청에 의한 이슈에 해당하는 경우 이슈 번호
  - `Closes` : 일반적인 개발과 관련된 이슈에 해당하는 경우 이슈 번호
  - `Fixes` : 버그 픽스, 핫 픽스 관련 이슈에 해당하는 경우 이슈 번호
  - `See also` : 커밋의 이슈와 연관되어 있는 이슈들이 존재 하는 경우, 또는 관련된 이슈들이 있는 경우 이슈 번호
8. 마무리
  - 마지막 꼬리말 라벨의 경우, `Resolves` 한 가지만 사용해도 되며 Github의 경우 `Commit Message` 또는 `Pull Request`의 경우 메시지에 있는 키워드로 이슈를 닫을 수 있는데 그때 위 라벨의 Resolves, Closes, Fixes로 닫을 수 있다.
  - 그 외 추가로 필요하다면 꼬리말에 이슈 관련 번호를 입력해서 커밋을 통해 실제 해당 커밋의 배경이 어떠한지를 추적 가능하게 하면 된다.
  - 제목 및 내용에서의 글자 제한을 두는 것을 `git log`를 통해 로그를 확인할 때 글자가 잘려 보이는 것들을 방지하기 위함도 있지만, 너무 길게 쓰는것 보다는 간결하게 쓰는 것을 선호하는 것도 있다.
