### ISSUE TITLE
2021-06-24 error report

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/algorithm_prectice#35]
## 문제점
https://github.com/Gyoung-min/algorithm_prectice/issues/31#issue-926242991
해당 issue를 수행하던 중 알수없는 오류가 발생한것 같습니다
해당 오류는 push 명령어가 수행되지 않는 오류입니다.

## 진행
해당 issue를 수행하기 위해 다음과 같이 진행했습니다.
1. 저장소를 fork 한다.
![fork](https://user-images.githubusercontent.com/78856207/123146806-46551d00-d499-11eb-9d4e-02c8c6f52cb4.PNG)
2. clone 수행
![clone](https://user-images.githubusercontent.com/78856207/123147669-473a7e80-d49a-11eb-840f-2713815ea0ca.PNG)
3. remote 수행
![remote](https://user-images.githubusercontent.com/78856207/123148029-b617d780-d49a-11eb-969b-0c796680cd93.PNG)
4. remote 현황
![remote2 PNG](https://user-images.githubusercontent.com/78856207/123148232-f11a0b00-d49a-11eb-95ec-376039ee24a4.PNG)
5. branch 생성 및 현황
![branch](https://user-images.githubusercontent.com/78856207/123148349-17d84180-d49b-11eb-84be-4093d532ceaa.PNG)
6. push 수행
![push1](https://user-images.githubusercontent.com/78856207/123148735-85846d80-d49b-11eb-96b8-b56216e79138.PNG)
![push2](https://user-images.githubusercontent.com/78856207/123148791-887f5e00-d49b-11eb-9db4-9d0aa458e84f.PNG)
7. 혹시 몰라 2개를 만들어서 2개 다 수행해 본 결과 해당 pull request 가 나오지 않았다.
![dddd](https://user-images.githubusercontent.com/78856207/123148897-aa78e080-d49b-11eb-8630-1275baffac26.PNG)
8. 해당 폴더가 만들어지기는 했다
![vhfej](https://user-images.githubusercontent.com/78856207/123149248-07749680-d49c-11eb-888e-8aa730cc06cb.PNG)

**Comment by lette1394** [comment]
@Gyoung-min 
피드백 드립니다

- 단계별로 수행한 내용을 정리한 내역이 매우 좋습니다 👍 
- 다음 링크를 참고해주세요. 더 나은 질문을 위한 가이드입니다. https://stackoverflow.com/help/how-to-ask
- 콘솔 창 (검은 창, `cmd` 창)은 모두 텍스트입니다. 굳이 이미지일 필요가 없어요ㅎㅎ 스크린샷보다는 `markdown code block`를 활용해주세요
- `fork`를 한 대상 `repository`를 보통 `upstream`이라고 합니다. `git remote` 등록한 내용에 대해서 이름을 바꾸는 명령어가 있어요. 그걸 참고하셔서 `GHP` 대신 `upstream` 이라고 이름을 바꿉시다.


-----


혹시 가이드 드린 내용에 PR 생성하는 관련 내용이 없던가요?
일반적으로 `upstream`(`GHP`가 뭔지는 모르겠지만 이후부터는 `upstream`이라고 말하겠습니다. `lette1394/git-practice repository`를 말합니다)에 직접 `push` 하지는 않습니다. 
보통 `local repo`에 새로운 브랜치를 생성해서, `origin`에 이 브랜치를 `push`를 하고, `upstream/<merge를 원하는 브랜치>` <--- `origin/<내가_작성한_브랜치>` 이렇게 요청을 합니다
더 이상 진행이 안되면, zoom 세션을 만들어서 같이 작업해보시죠
관련 내용은 git에 대해서 더 깊게 공부하시면 이해하실 수 있습니다

**Comment by Gyoung-min** [comment]
해당 내용을 확인 후 @eminem54 와 함께 해당 push 문제를 해결했습니다

**Comment by lette1394** [comment]
@Gyoung-min 
문제 해결한 내용도 여기에 정리해주세요~
어떻게 해결했는지, 무엇이 문제였는지, 왜 나는 그 문제되는 부분을 놓친것인지 등등

**Comment by Gyoung-min** [comment]
## 문제점
  - push 명령어 반응 없음

## 문제 파악
  - git 최조 설정시 이름과 이메일을 설정하지 않음

## 문제 해결
  - 이메일과 이름 설정
  - git을 설치 후 가장 먼저 행해야 하는 것은 사용자 이름과 이메일 주소를 설정하는 것이며 명령어는 다음과 같습니다
`$ git config --global user.name "user.name"`
`$ git config --global user.email user.email`

## 참고
https://git-scm.com/book/ko/v2/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-Git-%EC%B5%9C%EC%B4%88-%EC%84%A4%EC%A0%95

**Comment by lette1394** [comment]
- 공식 문서를 참고하는 것 매우매우x999 좋습니다!
- 처음엔 적응하기 어렵고 이해하기도 어렵지만, 그냥 블로그로 공부하는 것보다 훨씬 낫습니다

**Comment by lette1394** [comment]
고생하셨어요!
앞으로도 이렇게만 부탁드립니다ㅎㅎㅎ 💯💯💯
