### ISSUE TITLE
2021_06_05 daily logs

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/algorithm_prectice#4]
### 1. 오늘 공부한 내용

-  이것이 자바다 

    ch4,5 조건문과 반복문, 배열 이론 정리

<정리 내용>
  조건문 - if문
	     ㄴ if - else 문
             ㄴ if-else if 문
	     ㄴ 중첩 if 문
	     ㄴ switch 문

   임의 정수 만들기
 
   반복문  - for
                ㄴ while
	        ㄴ do - while 문 
    배열

`/*ch4 - 01) if문
		 
	제어문 - 프로그램의 흐름을 바꾸는 역할을 하는 문장
		 ㄴ조건문 : 조건에 따라 다른 문장이 수행 되도록 함
		 ㄴ반복문 : 특정 문장들을 반복하여 수행
					
		조건문- if문
				ㄴ 가장 기본적인 조건문(만일 ~ 이라면)
				 				
				<형태>
					   if(조건식) {
					   		조건이 참일 때 수행될 문장들;
					   					}
			
		02) 조건식의 다양한 예
				
				  - 조건식은 일반적으로 비교 연산자와 논리 연산자로 구성된다.
				
					ex) 90 <= x && x <= 100 / x가 90 이상 100 이하일 떄
						x < 0 || x > 100 / x 가 0보다 작거나 100보다 클 때
						
		03) 블럭{}
					
			-괄호를 이용하면 여러 문장을 하나의 단위로 묶을 수 있다.(; 마지막에 사용하지 않음을 주의하자)
					
						if(조건식) {
										조건이 참일 때 수행될 문장들;
							}<== 괄호를 기준으로 구분된다
										조건식에 상관 없이 수행되는 문장들;
		 04) if-else문
				
				조건문- if문
					ㄴ 가장 기본적인 조건문(만일 ~ 이라면)
					ㄴ if - else 문
					ㄴ else 블럭이 추가되어 조건식의 결과가 참이 아닐 때 else 문장을 수행하라는 의미이다.
						    어느 한 쪽이 참이면 다른 한 쪽이 거짓인 상반된 관계가 있을때 if 문을 if-else 문 
                                                   으로 바꿀 수 있다.
							
				<형태>
			   		if(조건식) {
			   					조건이 참일 때 수행될 문장들;
			   			} else {
			   					조건식이 거짓일 경우 수행될 문장들;
			   					}
			   				
		05) if-else if 문		
							
			조건문- if문
					ㄴ 가장 기본적인 조건문(만일 ~ 이라면)
				ㄴ if - else 문
					ㄴ else 블럭이 추가되어 조건식의 결과가 참이 아닐 때 else 문장을 수행하라는 의미이다.
					     어느 한 쪽이 참이면 다른 한 쪽이 거짓인 상반된 관계가 있을때 if 문을 if-else 문으로 
                                             바꿀 수 있다.	
				ㄴ if-else if 문
					 ㄴ 처리해야할 조건이 셋 이상일 떄 사용하는 조건식
					      조건에 맞는 문장이 없다면 마지막의 else 문장이 수행된다.
							  
					<형태>
				   	if(조건식) {
				   		 조건이 참일 때 수행될 문장들; , 거짓일 경우 다른 조건식과 비교
				   		} else if(조건식) {

				   	첫번째 조건식이 거짓이고 해당 조건식이 참일 경우 실행; , 거짓일 경우 다른 조건식과 비교

				   					} else if(조건식) {

				   	첫번째 조건식, 두번째 조건식이 거짓이고 해당 조건식이 참일 경우 실행; 
                                        , 거짓일 경우 다른 조건식과 비교

				   					} else {

				   								위의 모든 조건식이 거짓일 경우 수행

				   					}
				   		
		07) 중첩 if문	

			조건문- if문
					ㄴ 가장 기본적인 조건문(만일 ~ 이라면)
				  ㄴ if - else 문
					ㄴ else 블럭이 추가되어 조건식의 결과가 참이 아닐 때 else 문장을 수행하라는 의미이다.
					   어느 한 쪽이 참이면 다른 한 쪽이 거짓인 상반된 관계가 있을때 if 문을 if-else 문으로 바꿀 
                                           수 있다.	
				ㄴ if-else if 문
					ㄴ 처리해야할 조건이 셋 이상일 떄 사용하는 조건식
					     조건에 맞는 문장이 없다면 마지막의 else 문장이 수행된다.
				ㄴ 중첩 if 문
					ㄴif 문 블럭 안에 또 다른 if 문을 포함시키는 것, 중첩 횟수에 제한이 없다.
								
					<형태>
						if(조건식1) {
								/조건식1이 참일 경우 실행할 문장/
								if(조건식2) {
										/조건식1이 참이고 조건식2 역시 참일떄 실행할 문장/
									}else {
										/조건식1이 참이고 조건식2 역시 거짓일떄 실행할 문장/
										}
									
						}else {
								/조건식1이 거짓일 경우 실행할 문장/
								}
					
		09) swith 문

			조건문- if문
					ㄴ 가장 기본적인 조건문(만일 ~ 이라면)
				ㄴ if - else 문
					ㄴ else 블럭이 추가되어 조건식의 결과가 참이 아닐 때 else 문장을 수행하라는 의미이다.
					   어느 한 쪽이 참이면 다른 한 쪽이 거짓인 상반된 관계가 있을때 if 문을 if-else 문으로 바꿀 
                                            수 있다.	
                                 ㄴ if-else if 문
				          ㄴ 처리해야할 조건이 셋 이상일 떄 사용하는 조건식
						조건에 맞는 문장이 없다면 마지막의 else 문장이 수행된다.
				 ㄴ 중첩 if 문
					  ㄴif 문 블럭 안에 또 다른 if 문을 포함시키는 것, 중첩 횟수에 제한이 없다.
			          ㄴ switch 문
					 ㄴ if 조건문의 경우의 수가 많아지면 if를 계속 추가해야 하므로 조건식이 많아져서 복잡해 
                                              지고 처리 시간이 길어진다.
					     하지만 switch 문은 단 하나의 조건식으로 많은 경우의 수를 처리할 수 있고 표현도 간결 
                                             하여 알기 쉽다.
							           	  
			  <형태>
			- switch문은 조건식을 먼저 계산한 다음 , 그 결과와 일치하는 case 문으로 이동, 그 아래의 문장을 수 
                           행하며 break를 만다면 전체 switch 문을 빠져나간다.
									  
					 switch(조건식) {
									  		
							case 값1 : 
							         조건식의 결과가 값 1과 같은 경우 실행될 문장들
							...
							break; <--break는 case를 구분하는 역할, 없으면 break를 만날때 까지 모든 case를 
                                                                        수행한다.
							case 값2 :
								조건식의 결과 값이 값 2와 같은 경우 실행될 문장들
								...
								break;
						         default :
								조건식의 값이 위의 값들과 모두 일치하지 않을 경우 실행될 문장
									  
									  }switch_end
									  
									  
			10) switch문의 제약 조건
								
				- switch문의 조건식 결과는 정수 또는 문자열이여야 한다.
				- case문의 값은 정수 상수(문자 포함), 문자열만 가능하며, 중복되지 안하야 한다.
								
								ex)

								int num,result;
								final int ONE = 1;
								...
								
								switch(result) {
								    case '1' : => 가능 
								    case ONE : => 가능 <-정수 상수라 가능
								    case "YES" => 가능
								    case num: => 불가능(변수)
								    case 1.0: => 불가능(실수)
								}
									  
									  
			12) 임의 정수 만들기 Math.random()
						
								-난수를 얻기 위해서는 Math.random()을 사용
								 0.0이상 1.0미만의 하나의 숫자를 double 값으로 반환한다.
								 
								 ex) 1과 3 사이의 숫자를 구하여라
		
									0.0  <=  Math.random()  <  1.0
									
									0.0*3  <=  Math.random()*3  <  1.0*3
									
									0.0  <=  Math.random()*3  <  3.0
									
									(int)0.0  <= (int) Math.random()*3  < (int)3.0
									
									0 + 1  <=  Math.random()*3 + 1  <  3 + 1
									
									1 <= Math.random()*3 + 1 < 4
									
									==> 1~3 까지의 난수가 구해진다.
			
						13) for 문

								반복문 - 어떠한 작업이 반복적으로 수행되도록 할 때 사용됨
								   ㄴ for  - 반복 횟수를 알고 있을 떄 사용
								   ㄴ while - 반복 횟수를 모를 경우 사용
								  ㄴ do - while 문 
									  
								  
								  <형태>
								  
								 for(int i=1; i<=5; i++) {
									 /반복 수행 할 문장 또는 로직/
								 }
								 /조건이 끝날 경우 수행 할 문장 또는 로직/
								 
								 int i = 1 ; i <= 5;  i++
								 		ㄴ 초기화     ㄴ조건식     ㄴ증감식
							     
								 ㄴ 초기화 : 초기화는 반복문에 사용될 변수를 초기화 하는 부분 , 둘 이상의 
                                                                                     변수를 초기화 할수 있다(타입이 같아야 한다.)
								 ㄴ 조건식 : 참일 시 반복, 거짓 시 중단 즉 참일 동안 반복한다를 의미
								 ㄴ 증감식 : 매 반복마다 변수의 값이 증감식에 의해 점진적으로 변하다가 조 
                                                                                     건식이 거짓이 되어 for 문을 벗어나게 된다.
								 	                            ㄴ i++ / i-- / i += 2 / i *= 3
							           	  
							           	  
		  15) 중첩 for 문
		               for 문 안에 for 문을 포함시키는 것이 가능하며  
                                이를 중첩 for 문이라고 한다. 중첨 횟수에는 제한이 없다.
								
								ex) 5행 10열의 별을 찍어보자
							for(int j = 0 ; j<=5; j++) { <-그 행위를 5번 반복한다 3
								for(int i = 0; i <= 10; i++ ) {
									System.out.print(*);<- 별을 10개 찍는다 1
								}
								System.out.println(); <- 10개 찍으면 밑으로 내린다 2
							}
                           
			16) while 문

							while (조건식) { / 조건식이 거짓이 될때까지 반복한다./
								/참일때 수행할 로직 또는 문장/
							}
						    	/조건이 거짓일때 수행할 로직 또는 문장
						    
						    	vs for
						    	  ㄴ 초기화나 증감식이 필요하지 않을 경우 while 문이 적합하다.
						    	  
						    	  ex) int i = 1; <-초기화
						    			while(i<=10) { <- 조건식
						    				System.out.println(i);
						    				i++; <- 증감식
						    			}
						 
			 19) do-while 문

								do-while 문은 조건식을 뒤에서 만나기 때문에 1회는 무조건 실행하게 된다.
								
								<형태>
								do {
									 /최초 1회 실행 후 , 조건식이 참일 경우 계속 실행된다./
									} while(조건식);
						  
			20) break 문

						반복문 안에 break를 쓰면 break문은 자신이 포함된 가장 가까운 반복문을 벗어난다.
								
		         21) continue 문
								
					반복문 안에서 continue 문을 만나면 반복문 끝으로 이동하여 다음 반복문으로 넘어간다.
								
			 23) 이름 붙은 반복문
			
						하나 이상의 반복문을 벗어나기 위해 중첩 반복문 앞에 이름을 붙이고 break 
                                                와 continue를 지정해 줌으로써 탈출한다.*/`

		
- ch3 배열
`ch 5 -1) 배열이란?

				- 배열은 같은 타입의 여러 변수를 하나의 묶음으로 다루는 것
				- 각 저장공간이 연속적으로 배치되어 있다.
				
			
			  2) 배열의 선언과 생성
				
				 	<선언>
			  
			  		타입 [] 변수 이름
			 
			  			ㄴ int[] score;
			  			ㄴ String[] name;
			  			
			  		타입 변수이름 [];
			  			ㄴ int score[];
			  			ㄴ String name[];
			  			
			  		<셍성>
			  		
			  		타입 변수이름;
			  		변수 이름 = new 타입 [길이]
			  			ㄴ int[] score;
			  			  score = new int [5];
			  			  
			  			  
			  	3) 배열의 인덱스

					인덱스의 범위는 0부터 배열의 길이 -1 까지
					즉, 이상 미만의 개념이다.
					
					
					
				4) 배열의 길이 (배열이름.length)
					#)배열의 길이는 상수이다.

					int [] arr = new int[5];
					int tmp = arr.length;
					
					==> tmp = 5
							
					각 배열의 요소는 for 문으로 출력한다.
					
					int [] score = new int [6]
							
					for (int i=0; i<score.length; i++) {
						System.out.println(score[i]);
					}
			 
				5) 배열의 초기화

					- 배열은 생성과 동시에 자동적으로 기본값(0)으로 초기화되어 있다.
					- 원하는 값을 저장하려면 아래와 같이 사용하면 된다.
					
					int [] score = new int [6]
					
							score[1] = 50;
							score[2] = 60;
							.....
							
					int [] score = new int[] {10,20,30,40,50,60};
					int [] score = {10,20,30,40,50,60};
					
					int [] score = new int[5];
					
					for(int  i=0; i<score.length; i++) {
						score[i] = i*10;
					}
					
				6) 배열의 출력

					각 배열의 요소는 for 문으로 출력한다.

					int [] score = new int [6]
		
					for (int i=0; i<score.length; i++) {
							System.out.println(score[i]);
														}
				15) String 클래스의 주요 메소드
					
					- char charAt(int index) : 문자열에서 해당 위치에 있는 문자를 반환한다.
					- int length() : 문자열의 길이를 반환한다.
					- String substring(int from , int to) : 문자열에서 해당 범위의 문자열을 반환한다.
					- boolean equals(object obj) : 문자열의 내용이 같은지 확인한다. 같으면 결과는 true 다르면 false
					- char[] toCharArray() : 문자열을 문자배열 (char[])로 변환해서 반환한다.
					
					ex) String str = "ABCDE";
						char ch = str.charAt(3);
						==> D를 ch에 저장
								
						String str = "012345"
						String tmp = str.substring(1,4);
						System.out.println(tmp);
						==> 123 출력

								
				  18) 2차원 배열의 선언
					
							<선언>
				  
				  				타입[][] 변수이름;    int [][] score;
				  				타입 변수이름 [][];	   int score [][];
				  				타입[] 변수이름[];	   int[] score [];
			
				  				ex) int[][]score = new int [5][4] <= 5행 4열 배열 생성
					
				   19) 2차원 배열의 인덱스
											
						5x4 배열 기준
						
						[0][0] [0][1] [0][2]......				
						[1][0] [1][1] [1][2]......
						[2][0]
						[3][0]
						......
						
					20) 배열의 초기화
				
							int[][]score = new int [][] {{1,2,3},{4,5,6}};(new int [][] 생략 가능)
						
							int[][]arr= {
										 {1,2,3},
										 {4,5,6},
										 {7,8,9}
										 };
						
					24) Arrays로 배열 다루기
						
							- 배열의 비교 출력 
							  ㄴ	equals() , toString()
							  
							  ex) toString 

								int[]arr = {0,1,2,3,4};
								int[][] arr2D = {{11,12},{21,22}};
								
								System.out.println(Arrays.toString(arr)); => [0,1,2,3,4]
															ㄴ toString은 일차원 배열에서만 사용 가능
															
								System.out.println(Arrays.deepToString(arr2D)); [[11,12],[21,22]]
								==> 배열의 모든 요소를 문자열로 출력한다.
							  
							   ex) equals
							  
								String[][] str2D = new String[][] {{AAA,BBB},{aaa,bbb}}
								String[][] str2D2 = new String[][] {{AAA,BBB},{aaa,bbb}}
								
							System.out.println(Arrays.equals(str2D, str2D2)); =>false equals는 일차원 배열에만 사용 가능
							System.out.println(Arrays.deepEquals(str2D,str2D2)); =>true
								
							   ex) copyof

								int[] arr = {0,1,2,3,4};
								int[] arr2 = Arrays.copyOf(arr, arr.length); =>arr2 = [0,1,2,3,4]
								int[] arr3 = Arrays.copyOf(arr, 3); =>arr3 = [0,1,2] 0이상~3미만
								
							  ex) sort

								int[] arr = {3,2,0,1,4}
								Array.sort(arr);
								System.out.println(Arrays.toString(arr)); => [0,1,2,3,4,]*/
`
ch4 반복문,조건문 문제 풀이
`/*4-1 다음의 문장들을 조건식으로 표현하여라*/
		
		/*1. int형 변수 x가 10보다 크고 20보다 작을 때 true인 조건식*/
		
		int x = 15;
		
		if(10<x&&x<20) {
			System.out.println("true");
		}
		
		/*2. char형 변수 ch가 공백이나 탭이 아닐 때 true인 조건식*/
		
		char ch = '1';
		
		if(' '!=ch && '\t'!=ch) {
			System.out.println("true");
		}
		
		/*3. char형 변수 ch가 'x' 또는 'X' 일때  true인 조건식*/
		
		if('x'==ch||'X'==ch) {
			System.out.println("true");
		}
		
		/*4. char형 변수가 ch가 숫자 ('0'~'9') 일 때 true인 조건식*/
		
		if(ch>='1' && ch<='9') {
			System.out.println("true");
		}
		
		/*5. char 형 변수 ch가 영문자 일때 true인 조건식*/
		
			if((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z')) {
				System.out.println("true"); //아스키코드 문제
			}
		
		/*6. int 형 변수 year가 400으로 나눠 떨어지거나 또는 4로 나누어 떨어지고 100으로 나눠 떨어지지 
			않을때 true인 조건식*/
			
			int year = 400;
			
			if((year%400==0)||( year%4 == 0 && year%100!=0)) {
				System.out.println("true");
			}
		
		/*7. boolean형 변수 powerOn이 false 일 때 ture인 조건식*/
			
			boolean powerOn= false;
			
			if(powerOn != true) {
				System.out.println("true");
			}
			
			
		/*8. 문자열 참조변수 str이 "yes"일 때 true인 조건식*/
			
			String str = "yes";
			
			if("yes".equals(str)) {
				System.out.println("true");
			}`

- 알고리즘 1문항
`	/*Given integer array nums, 
		return the third maximum number in this array.
		If the third maximum does not exist, 
		return the maximum number.
		
		Input: nums = [3,2,1]
		Output: 1
		Explanation: The third maximum is 1.
		
		Input: nums = [1,2]
		Output: 2
		Explanation: 
		The third maximum does not exist, 
		so the maximum (2) is returned instead.
		*/
		
		Scanner sc1 = new Scanner(System.in);
		
		
		
		int [] arr = new int [4];
		int size = arr.length;
		
		int max = arr[0];
		
		// 배열을 입력 받음
		for(int i = 0; i< size; i++) {
		System.out.println("숫자를 입력해주세요 : ");
		arr[i] = sc1.nextInt();
		}
		
		//for 문을 통해 가장 큰 값이 max에 저장되도록 함
		for(int i = 0; i<size; i++) {
			if(arr[i]>max) {
				max = arr[i];
			}
		}	
		if (size < 3) { //배열이 3보다 작다면 리턴
			return;
		}
		
		int second = Integer.MIN_VALUE; 
		for(int i =0; i< size; i++) {
			if(arr[i]>second && arr[i]<max) {
								//최대값 전에서 멈춤
				//최대값 전이 대입됨
				second = arr[i];
			}	
		}
		
		int third = Integer.MIN_VALUE;
		for(int i = 0 ; i < size; i++) {
			if(arr[i]>third && arr[i]<second) {
								//2번쨰 최대값 전에 멈춤
				//3번쨰 값이 대입됨
				third = arr[i];
			}
			
	}
		if(size>3) {
			System.out.println(max);
		}
		
		if(size <= 3) {
			System.out.println(third);
		}`

- 질문
 리스트(배열)의 크기를 미리 정하지 않고 scanner로 리스트(배열)을 받아 배열의 크기가 scanner를 통해 커지거나 작아지거나 할수 있는 가변 리스트(배열)을 만들수 있나요?

**Comment by lette1394** [comment]
@Gyoung-min 
## 피드백

### 1. markdown 익히기
- github은 `markdown` 문법을 지원합니다. 
- `markdown`이 무엇인지, 어떤 목적으로 사용되는지 **간단하게** 조사해보세요 (너무 깊게는 필요하지 않아요ㅎㅎ) 
- 기본적인 문법을 익혀서 다음 issue 부터 사용해주세요. 가독성이 높게 작성 부탁드립니당

### 2. 공부한 내용의 정리
- 혹시 정리를 위해 투자하는 시간이 얼마나 되나요?
- 이해하는게 더 중요합니다. 여기에 적기 위한 시간이 너무 길다면 최대한 짧게 핵심만 정리해주세요. 제가 피드백을 드릴 수 있는 정도면 충분합니다 
- 너무 간결하면 또 제가 자세히 적어달라고 말씀을 드릴게요ㅎㅎ
- 일단 지금은 너무 자세한 거 같습니다! 정리하면서 다시 학습하는거라면 문제 없지만 시간 투자를 너무 하시는거같아서 말씀드려용
- 중요한 건 **진도를 빠르게 빼는 것**입니다... 우리가 갈 길이 멀기 때문에ㅎㅎ


### 3. `switch` 에서 `break`를 빼먹는 경우 어떻게 될까요?
- `break`를 사용하지 않는 경우가 **일반적인지** 생각해보세요
- 언제 `if-else`를 사용하는지, 언제 `switch`를 사용하는지 생각해보세요. 둘 다 기능은 똑같은거 같은데...


### 4. Random seed 
- 컴퓨터는 진정한 random을 만들 수 없다고 합니다. (컴퓨팅 한계)
- 이를 극복하기 위한 `seed` 개념에 대해서 **간략히** 알아보세요


### 5. `goto` keyword
- java에는 `label` 이라는 개념이 있습니다
- 이 label과 `goto` keyword를 이용해 반복문을 만들 수도 있는데요, 이에 대해 **간단히** 알아보세요



### 6. array copy
- 두 배열을 복사하는 방법은 무엇일까요?
- 깊은 복사, 얕은 복사에 대해 **자세히** 알아보세요
- (심화) pointer 개념이 여기서 사용됩니다. pointer와 array(배열)은 무슨 관계가 있는지 **자세히** 알아보세요


### 7. String class (심화)
- `String` class는 사실 `char[]`에 이런 저런 메서드를 추가한 클래스에 불과합니다
- `String` class를 자세히 뜯어보고 이를 확인하세요
- 무슨 말인지 모르겠다면 넘어가도 좋습니다 
- 시간이 너무 오래걸려도 넘어가세요


### 8. 문제 풀이
- 아주 좋습니다!
- 많이 사용해야 익숙해집니다
- 더 많은 문제를 풀어보고, **반드시 매일매일 java code를 작성해보도록** 하세요. 무엇이든 좋습니다. 했던거를 다시 작성해봐도 좋고, 책을 그대로 따라해봐도 좋아요.
- 반복만이 지름길입니다. 
- 계속 말씀드렸듯, java를 아주 능숙하게 다룰 줄 알아야 다음 단계로 넘어가기 쉽습니다.


### 가독성
- 아래 두 코드중 어느것이 더 쉽게 읽히는지 생각해보고, 그 이유를 알려주세요
- `7. boolean형 변수 powerOn이 false 일 때 ture인 조건식`에 대한 내용입니다

```java
// 1번 코드
boolean powerOn = ...;
if (powerOn != true) {
  System.out.println("전원이 꺼졌습니다");
}
```

```java
// 2번 코드
boolean powerOff = ...;
if (powerOff) {
  System.out.println("전원이 꺼졌습니다");
}
```





## 질문
- 일단, `List`와 `배열`은 다릅니다
- 배열은 가변적일 수 없습니다. 반드시 선언 할 때 길이를 정해야 합니다
- 따라서 사용자의 입력이 무엇이 들어올 지 모른다면, 충분한 수의 배열의 길이를 미리 선언해놓고 사용하거나 
- 아니면 가지고 있는 배열보다 더 큰 길이의 입력이 들어오면 그때그때 복사하는 방법 밖에 없습니다
- (심화) 이런 문제를 해결하기 위해서 다양한 자료구조가 나왔고, 이를 java에서는 미리 구현해놓았는데요. 관련한 내용을 찾아보는 것도 좋을거같습니다ㅎㅎ 
- 키워드는 `List`, `LinkedList`, `ArrayList` 입니다 
- 자료구조는 현재 단계에서는 심화내용이니, 천천히 하셔도 됩니다
- 빨리 자료구조 책을 좀 알아봐야겠네요..ㅠ



## 종합
- 오늘 하루도 고생 많으셨습니다
- 빠르게 java를 마무리하고 다음 책으로 넘어가시죠
- 자료구조는 당분간 holding 할게요. 풀 수 있는 알고리즘 문제를 하루에 하나만 하고, 나머지는 기본적인 java 문법을 익히는데 올인하시죠!
- 아주 잘 하고 계십니다ㅎㅎ 파이팅!! 👍💯🔥🔥🔥

**Comment by Gyoung-min** [comment]
개념을 정리 하는 것은 다른 곳에 했다가 깃 허브로 복사 붙여넣기 하고 있는 것입니다.
이것이 자바다를 하루에 2ch씩 너무 내용이 길다면 
1 ch 씩 진도를 나간 후 (약 9일정도 소요), 다음 자료구조/알고리즘을 학습하면서
이것이 자바다를 1ch 씩 정리한 것 암기 및 예제와 연습 문제로 복습을 할 계획을 하고 있습니다.

1ch 당 약 길면 3시간 보통 2시간 정도의 시간이 소요됩니다.

해당 깃 허브에는 복붙이 아닌 가독성 있고 더 간략하게 요약해서 올리도록 하겠습니다.

**Comment by Gyoung-min** [comment]
가독성 측면에서는 전자보단 후자가 좋아보입니다.
코딩을 접해보지 않은 사람은 != 해당 기호가 무엇을 의미하는지 알수 없고
후자의 경우 기호를 사용하지 않고 poweroff일 경우 전원이 꺼진다 즉, 
off와 꺼짐이라는 같은 의미를 가진 단어로 조합해 그 누가 보아도 해당 if 문이 무엇인지를 알수 있도록 코딩되어 있습니다.

**Comment by lette1394** [comment]
@Gyoung-min 
핵심은 가독성입니다 
사람이 코드를 짜고 사람이 그 코드를 읽기 때문에 항상 읽기 쉽게 작성하는게 정말 중요합니다

"파워가 켜지지 않으면, off 라고 출력하라" 
vs
"파워가 꺼졌으면, off 라고 출력하라" 

~하지 않으면 ~해라 라고 하는 것보다
~하면 ~해라 라고 하는게 좋습니다
`if( ~ )` 안은 항상 긍정문으로 작성합시다
