### ISSUE TITLE
repository 알람 받기

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#5]
- 이 github repository에 새로운 이슈가 생성되거나 댓글이 작성된 경우 **실시간 알람**을 받을 수 있는 방법을 생각해보고, 핸드폰이나 컴퓨터에 적용하세요
- 힌트는 github app 혹은 email notification 입니다

**Comment by Gyoung-min** [comment]
깃허브 앱 설치 및 notification 이메일 알람 설정 했습니다!

**Comment by lette1394** [comment]
@Gyoung-min 
github app 폰 알림도 설정해주세요~~

**Comment by Gyoung-min** [comment]
앱 역시 notification 설정을 통해 inbox에 해당 알림이 오도록 설정했습니다
