### ISSUE TITLE
Issue creation format 

### ISSUE THREAD

**Issue by lette1394** [Gyoung-min/algorithm_prectice#8]
어떤 이슈는 `2021-06-04 daily logs`
어떤 이슈는 `2021_06_05 daily logs`
인데요,

- 시각/날짜를 표현하는 표준을 알아보세요 (keyword: `iso date format`)
- 기존에 생성된 이슈를 포함해서, 하나의 방식으로 통일 해주세요
- github `assignee`가 무엇인지 알아보고, 이슈가 생성될 때 `assignee`를 항상 등록해주세요

**Comment by Gyoung-min** [comment]
시간/날짜 표준 ISO 8601 내용 확인 후 모든 이슈 날짜 표시를 수정했습니다.
모든 이슈의 양식을 하나로 통일하고 불필요한 내용은 삭제했습니다.
assignee은 해당 작업의 담당자로 모든 이슈에 assignee을 등록했습니다
